/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        surface: '#fff9ec',
        'surface-dim': '#e0dac9',
        'surface-bright': '#fff9ec',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#faf3e2',
        'surface-container': '#f4eddd',
        'surface-container-high': '#eee8d7',
        'surface-container-highest': '#e9e2d2',
        'on-surface': '#1e1c12',
        'on-surface-variant': '#50443f',
        'inverse-surface': '#333025',
        'inverse-on-surface': '#f7f0df',
        outline: '#82746e',
        'outline-variant': '#d4c3bc',
        'surface-tint': '#795744',
        primary: '#32190b',
        'on-primary': '#ffffff',
        'primary-container': '#4b2e1e',
        'on-primary-container': '#bf957f',
        'inverse-primary': '#eabda6',
        secondary: '#7a5900',
        'on-secondary': '#ffffff',
        'secondary-container': '#fdbc13',
        'on-secondary-container': '#6b4d00',
        tertiary: '#361800',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#502c0e',
        'on-tertiary-container': '#c7926c',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbca',
        'primary-fixed-dim': '#eabda6',
        'on-primary-fixed': '#2d1507',
        'on-primary-fixed-variant': '#5f3f2e',
        'secondary-fixed': '#ffdea3',
        'secondary-fixed-dim': '#fdbc13',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4200',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#f4bb92',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#653d1e',
        background: '#fff9ec',
        'on-background': '#1e1c12',
        'surface-variant': '#e9e2d2',
      },
      fontFamily: {
        manrope: ['Manrope', 'sans-serif'],
        'work-sans': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        h1: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.01em', fontWeight: '500' }],
        button: ['16px', { lineHeight: '1.0', fontWeight: '600' }],
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(75, 46, 30, 0.05)',
        'card-hover': '0px 10px 30px rgba(75, 46, 30, 0.1)',
        'nav': '0px 4px 20px rgba(75, 46, 30, 0.1)',
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};